# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Docker

on:
  #ela é executada somente quandofor chamada
  workflow_call:
  
jobs:
  docker:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #estamos usando outro repositório
    
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v2.9.0
      
      #Fazendo login em um repositório docker
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: gabrielnovaisgs
        # Password or personal access token used to log against the Docker registry
        password: # optional
        #
