# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
#Define quando deve ser executado a rotina
#Ex: quando realizar um push ou um pull request nesse branch
on:
  push:
    branches: [ "Aula_1" ]
  pull_request:
    branches: [ "Aula_1" ]

#quais são os trabalhos realizados
jobs:

#test é uma das tarefas que vai ser executada
  test:
    #onde essa tarefa será executada
    runs-on: ubuntu-latest
    #passo a passo que sera executado
    steps:
    #primeiro utiliza um repositório para fazer a tarefa
    - uses: actions/checkout@v3
    
    #primeiro passo (nome setup go)
    - name: Set up Go
      uses: actions/setup-go@v3
      # Define a versão do Go 1.19
      with:
        go-version: 1.19
    #passo 2: faz o build do banco
    - name: Build-DB
     #executa o comando dentro da maquina
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
    
      
  build:
  #Define que precisa esperar a rotina de teste terminar para começar o build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
